format = """
($cmd_duration\n)\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$hg_branch\
$pijul_channel\
$memory_usage\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

right_format = """
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal"""

add_newline = true
scan_timeout = 30

palette = 'nord'

# ディレクトリ表示
[directory]
truncation_length = 10
truncate_to_repo = true
truncation_symbol = "…/"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'cyan bold'
conflicted = '! '           # 競合 - 緊急対応が必要
ahead = '↑${count} '        # プッシュ待ち - リモートへ送信が必要
behind = '↓${count} '       # プル待ち - リモートから取得が必要
untracked = '?${count} '    # 未追跡 - 新しいファイルが存在
modified = '~${count} '     # 変更済み - ローカルで変更されたファイル
staged = '+${count} '       # ステージ済み - コミット準備完了

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[cmd_duration]
show_milliseconds = true
format = '[- $duration -]($style)'
style = 'white'

# プログラミング言語
[nodejs]
format = "[$symbol$version]($style) "
symbol = "󰎙 "

[python]
format = "[$symbol$pyenv_prefix$version(\\($virtualenv\\))]($style) "
symbol = "󰌠 "

[rust]
format = "[$symbol$version]($style) "
symbol = "󱘗 "

[golang]
format = "[$symbol$version]($style) "
symbol = "󰟓 "

[java]
format = "[$symbol$version]($style) "
symbol = "󰬷 "

[php]
format = "[$symbol$version]($style) "
symbol = "󰌟 "

[ruby]
format = "[$symbol$version]($style) "
symbol = "󰴭 "

[swift]
format = "[$symbol$version]($style) "
symbol = "󰛥 "

[kotlin]
format = "[$symbol$version]($style) "
symbol = "󱈙 "

[scala]
format = "[$symbol$version]($style) "
symbol = "󰈺 "

[dart]
format = "[$symbol$version]($style) "
symbol = "󰻂 "

[dotnet]
format = "[$symbol$version]($style) "
symbol = "󰪮 "

[c]
format = "[$symbol$version]($style) "
symbol = "󰙱 "

[elixir]
format = "[$symbol$version \\(OTP $otp_version\\)]($style) "
symbol = "󰍉 "

[elm]
format = "[$symbol$version]($style) "
symbol = "󰻃 "

[erlang]
format = "[$symbol$version]($style) "
symbol = "󰚌 "

[haskell]
format = "[$symbol$version]($style) "
symbol = "󰲒 "

[julia]
format = "[$symbol$version]($style) "
symbol = "󰌬 "

[lua]
format = "[$symbol$version]($style) "
symbol = "󰢱 "

[nim]
format = "[$symbol$version]($style) "
symbol = "󰆥 "

[ocaml]
format = "[$symbol$version]($style) "
symbol = "󰘧 "

[perl]
format = "[$symbol$version]($style) "
symbol = "󰌟 "

[purescript]
format = "[$symbol$version]($style) "
symbol = "󰆦 "

[zig]
format = "[$symbol$version]($style) "
symbol = "󰚌 "

# インフラ・クラウド
[docker_context]
format = "[$symbol$context]($style) "
symbol = "󰡨 "

[aws]
format = "[$symbol$profile(\\($region\\))(\\[$duration\\])]($style) "
symbol = "󰸏 "

[gcloud]
format = "[$symbol$account(@$domain)(\\($region\\))]($style) "
symbol = "󱇶 "

[azure]
format = "[$symbol$subscription]($style) "
symbol = "󰠅 "

[kubernetes]
format = "[$symbol$context(\\($namespace\\))]($style) "
symbol = "☸ "

# ツール
[terraform]
format = "[$symbol$workspace]($style) "
symbol = "󱁢 "

[helm]
format = "[$symbol$version]($style) "
symbol = "⎈ "

[vagrant]
format = "[$symbol$version]($style) "
symbol = "󰳐 "

[conda]
format = "[$symbol$environment]($style) "
symbol = "󰔬 "

[nix_shell]
format = "[$symbol$state(\\($name\\))]($style) "
symbol = "󱄅 "

[package]
format = "[$symbol$version]($style) "
symbol = "󰏗 "

[cmake]
format = "[$symbol$version]($style) "
symbol = "󰔶 "

[gradle]
format = "[$symbol$version]($style) "
symbol = "󰉡 "

[meson]
format = "[$symbol$project]($style) "
symbol = "⬢ "

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'