env:
  TERM: xterm-256color

import:
  # Alacritty Theme(https://github.com/alacritty/alacritty-theme)
  - ~/.config/alacritty/themes/themes/one_dark.yaml
  # - ~/.config/alacritty/themes/themes/gruvbox_dark.yaml

window:
  decorations: buttonless # タイトルバーとボタンを非表示
  startup_mode: Maximized # 最大で起動する
  opacity: 1 # 背景を透過させる
  padding:
    x: 10
    y: 4
  decorations_theme_variant: Dark # ダークテーマ

scrolling:
  history: 10000

font:
  size: 13 # フォントサイズ
  normal:
    family: "PlemolJP35 Console NF"
    style: Regular
  bold:
    family: "PlemolJP35 Console NF"
    style: Bold
  italic:
    family: "PlemolJP35 Console NF"
    style: Italic
  bold_italic:
    family: "PlemolJP35 Console NF"
    style: Bold Italic
  offset:
    y: 1

selection:
  save_to_clipboard: true # 選択範囲をクリップボードにコピーする

cursor:
  style:
    shape: Block
    blinking: On

# keybinding
key_bindings:
  - {
      key: Comma,
      mods: Command,
      command: { program: "sh", args: ["-c", "open ~/.config/alacritty/alacritty.yml"] },
    }
  # - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: Left, mods: Alt, chars: "\x1bb" } # one word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # one word right
  - { key: Left, mods: Command, chars: "\x1bOH", mode: AppCursor } # Home
  - { key: Right, mods: Command, chars: "\x1bOF", mode: AppCursor } # End
    # tmux用設定
  - { key: T, mods: Command, chars: "\x01\x63" } # C-a cを送信（Cmd+tで新規ウインドウ）
  - { key: D, mods: Command, chars: "\x01\x25" } # C-a %を送信（Cmd+dでペインを横分割）
  - { key: D, mods: Command|Shift, chars: "\x01\x22" } # C-a "を送信（Cmd+Shift+dでペインを縦分割）
  - { key: W, mods: Command, chars: "\x01\x78" } # C-a xを送信（Cmd+wでペインを削除）
  # - { key: N, mods: Command, chars: "\x01\x63" } # C-a cを送信（Cmd+nで新規ウィンドウ）
  - { key: N, mods: Command, chars: "\x01\x6a" } # C-a jを送信（Cmd+nでポップアップウィンドウ）
  - { key: LBracket, mods: Command, chars: "\x01\x6F" } # C-a oを送信（Cmd+]で次のペインに移動）
  - { key: RBracket, mods: Command, chars: "\x01\x3B" } # C-a ;を送信（Cmd+[で前のペインに移動）
  - { key: Left, mods: Command | Shift, chars: "\x01\x1bOD" } # C-a ←を送信（Cmd+Shift+←で左のペインに移動）
  - { key: Right, mods: Command | Shift, chars: "\x01\x1bOC" } # C-a →を送信（Cmd+Shift+→で右のペインに移動）
  - { key: Up, mods: Command | Shift, chars: "\x01\x1bOA" } # C-a ↑を送信（Cmd+Shift+↑で上のペインに移動）
  - { key: Down, mods: Command | Shift, chars: "\x01\x1bOB" } # C-a ↓を送信（Cmd+Shift+↓で下のペインに移動）
  - { key: Key1, mods: Command, chars: "\x01\x31" } # C-a 1を送信（Cmd+1で1番目のウインドウに移動）
  - { key: Key2, mods: Command, chars: "\x01\x32" } # C-a 2を送信（Cmd+2で2番目のウインドウに移動）
  - { key: Key3, mods: Command, chars: "\x01\x33" } # C-a 3を送信（Cmd+3で3番目のウインドウに移動）
  - { key: Key4, mods: Command, chars: "\x01\x34" } # C-a 4を送信（Cmd+4で4番目のウインドウに移動）
  - { key: Key5, mods: Command, chars: "\x01\x35" } # C-a 5を送信（Cmd+5で5番目のウインドウに移動）
  - { key: Key6, mods: Command, chars: "\x01\x36" } # C-a 6を送信（Cmd+6で6番目のウインドウに移動）
  - { key: Key7, mods: Command, chars: "\x01\x37" } # C-a 7を送信（Cmd+7で7番目のウインドウに移動）
  - { key: Key8, mods: Command, chars: "\x01\x38" } # C-a 8を送信（Cmd+8で8番目のウインドウに移動）
  - { key: Key9, mods: Command, chars: "\x01\x39" } # C-a 9を送信（Cmd+9で9番目のウインドウに移動）

shell:
  program: /bin/zsh
  args:
    - -l
    - -i
    - -c
    - 'tmux a -t default || tmux new -s default\; source ~/.config/tmux/default.session.conf'
