import = ["~/.config/alacritty/themes/themes/one_dark.toml"]

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "PlemolJP35 Console NF"
style = "Bold"

[font.bold_italic]
family = "PlemolJP35 Console NF"
style = "Bold Italic"

[font.italic]
family = "PlemolJP35 Console NF"
style = "Italic"

[font.normal]
family = "PlemolJP35 Console NF"
style = "Regular"

[font.offset]
y = 1

[[keyboard.bindings]]
key = "Comma"
mods = "Command"

[keyboard.bindings.command]
args = ["-c", "open ~/.config/alacritty/alacritty.yml"]
program = "sh"

# ----------
# Keybindings
# ----------
# one word left
[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"
# one word right
[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"
# Home
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"
# End
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

# ----------
# Tmux
# ----------
# C-a cを送信（Cmd+tで新規ウインドウ）
[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"
# C-a %を送信（Cmd+dでペインを横分割）
[[keyboard.bindings]]
chars = "\u0001%"
key = "D"
mods = "Command"
# C-a "を送信（Cmd+Shift+dでペインを縦分割）
[[keyboard.bindings]]
chars = "\u0001\""
key = "D"
mods = "Command|Shift"
# C-a xを送信（Cmd+wでペインを削除）
[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"
# C-a jを送信（Cmd+nでポップアップウィンドウ）
[[keyboard.bindings]]
chars = "\u0001j"
key = "N"
mods = "Command"
# C-a oを送信（Cmd+]で次のペインに移動）
[[keyboard.bindings]]
chars = "\u0001o"
key = "LBracket"
mods = "Command"
# C-a ;を送信（Cmd+[で前のペインに移動）
[[keyboard.bindings]]
chars = "\u0001;"
key = "RBracket"
mods = "Command"
# C-a ←を送信（Cmd+Shift+←で左のペインに移動）
[[keyboard.bindings]]
chars = "\u0001\u001BOD"
key = "Left"
mods = "Command | Shift"
# C-a →を送信（Cmd+Shift+→で右のペインに移動）
[[keyboard.bindings]]
chars = "\u0001\u001BOC"
key = "Right"
mods = "Command | Shift"
# C-a ↑を送信（Cmd+Shift+↑で上のペインに移動）
[[keyboard.bindings]]
chars = "\u0001\u001BOA"
key = "Up"
mods = "Command | Shift"
# C-a ↓を送信（Cmd+Shift+↓で下のペインに移動）
[[keyboard.bindings]]
chars = "\u0001\u001BOB"
key = "Down"
mods = "Command | Shift"
# C-a 1を送信（Cmd+1で1番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"
# C-a 2を送信（Cmd+2で2番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"
# C-a 3を送信（Cmd+3で3番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"
# C-a 4を送信（Cmd+4で4番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"
# C-a 5を送信（Cmd+5で5番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"
# C-a 6を送信（Cmd+6で6番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"
# C-a 7を送信（Cmd+7で7番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"
# C-a 8を送信（Cmd+8で8番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"
# C-a 9を送信（Cmd+9で9番目のウインドウに移動）
[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true # 選択範囲をクリップボードにコピーする

[shell]
args = ["-l", "-i", "-c", 'tmux a -t default || tmux new -s default\; source ~/.config/tmux/default.session.conf']
program = "/bin/zsh"

[window]
decorations = "buttonless" # タイトルバーとボタンを非表示
decorations_theme_variant = "Dark"
opacity = 1
startup_mode = "Maximized" # 最大で起動する

[window.padding]
x = 10
y = 4
